version: '3.3'

services:
  mongodb:
    container_name: mongodb
    expose:
      - "27017"
    image: mongo
    logging:
      driver: "none"
    ports:
      - "27017:27017"
  
  user:
    image: node:10.12-slim
    container_name: user
    depends_on:
      - mongodb
    entrypoint: npx nodemon src/services/users/server/main.js
    ports:
      - "8000:8000"
    volumes:
      - "${PWD}/:/app"
    working_dir: /app
  
  test:
    image: node:10.12-slim
    container_name: test
    depends_on:
      - mongodb
    entrypoint: npx nodemon src/services/test/server/main.js
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}/:/app"
    working_dir: /app

  # cypress:
  #   build:
  #     context: .docker/cypress
  #     dockerfile: Dockerfile
  #   container_name: cypress
  #   privileged: true
  #   depends_on:
  #     - aos_server
  #   entrypoint: sh /scripts/entrypoint.sh
  #   external_links: 
  #     - aos_server
  #   ipc: host
  #   volumes:
  #     - "${PATH_APP}.docker/cypress/scripts:/scripts"
  #     - "${PATH_APP}:/test"

  # aos_jest:
  #   image: goaos/node-intl:0.1.1
  #   container_name: "${PATH_APP}_jest"
  #   entrypoint: sh /scripts/jest.sh
  #   volumes:
  #     - "${PATH_APP}:/app"
  #     - "${PATH_APP}/.docker/unit_test:/scripts"
  #   working_dir: /app
  # aos_linter:
  #   image: node:8.9.3
  #   container_name: "${PATH_APP}_linter"
  #   entrypoint: sh /scripts/lint.sh
  #   volumes:
  #     - "${PATH_APP}:/app"
  #     - "${PATH_APP}/.docker/unit_test:/scripts"
  #   working_dir: /app
